# Generated by Django 3.2.7 on 2021-09-18 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import floor.function


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='品名CD')),
                ('name', models.CharField(max_length=50, verbose_name='品名')),
                ('sales_unit', models.CharField(blank=True, choices=[('m', 'm'), ('㎡', '㎡'), ('ケース', 'ケース'), ('セット', 'セット'), ('巻', '巻'), ('箱', '箱'), ('本', '本'), ('枚', '枚')], max_length=20, null=True, verbose_name='販売単位')),
                ('catalog_retail_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='カタログ上代価格')),
                ('catalog_retail_unit', models.CharField(blank=True, choices=[('m', 'm'), ('㎡', '㎡'), ('ケース', 'ケース'), ('セット', 'セット'), ('巻', '巻'), ('箱', '箱'), ('本', '本'), ('枚', '枚')], max_length=20, null=True, verbose_name='カタログ上代単位')),
                ('thickness', models.FloatField(blank=True, null=True, verbose_name='厚み(mm)')),
                ('standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('display_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='表示用規格')),
                ('retail_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='上代')),
                ('expenses', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='入目')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='シリーズCD')),
                ('name', models.CharField(max_length=50, verbose_name='シリーズ名')),
                ('kana_name', models.CharField(max_length=50, verbose_name='シリーズ名(かな)')),
            ],
            options={
                'verbose_name': 'シリーズ',
                'verbose_name_plural': 'シリーズ',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='品種CD')),
                ('name', models.CharField(max_length=50, verbose_name='品種名')),
                ('kana_name', models.CharField(max_length=50, verbose_name='品種名(かな)')),
            ],
            options={
                'verbose_name': '品種',
                'verbose_name_plural': '品種',
            },
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='ファイル名は英数字', upload_to=floor.function.upload_product_image_path)),
                ('triple_image', models.ImageField(blank=True, null=True, upload_to=floor.function.upload_product_triple_image_path)),
                ('hsv_report', models.BinaryField(blank=True, null=True)),
                ('rgb1_r', models.FloatField(blank=True, null=True)),
                ('rgb1_g', models.FloatField(blank=True, null=True)),
                ('rgb1_b', models.FloatField(blank=True, null=True)),
                ('rgb2_r', models.FloatField(blank=True, null=True)),
                ('rgb2_g', models.FloatField(blank=True, null=True)),
                ('rgb2_b', models.FloatField(blank=True, null=True)),
                ('rgb3_r', models.FloatField(blank=True, null=True)),
                ('rgb3_g', models.FloatField(blank=True, null=True)),
                ('rgb3_b', models.FloatField(blank=True, null=True)),
                ('h_per_5', models.FloatField(blank=True, null=True)),
                ('h_per_50', models.FloatField(blank=True, null=True)),
                ('h_per_95', models.FloatField(blank=True, null=True)),
                ('s_per_5', models.FloatField(blank=True, null=True)),
                ('s_per_50', models.FloatField(blank=True, null=True)),
                ('s_per_95', models.FloatField(blank=True, null=True)),
                ('v_per_5', models.FloatField(blank=True, null=True)),
                ('v_per_50', models.FloatField(blank=True, null=True)),
                ('v_per_95', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.product')),
            ],
            options={
                'verbose_name': '商品レポート',
                'verbose_name_plural': '商品レポート',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='floor.series', verbose_name='シリーズ'),
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='floor.variety', verbose_name='品種'),
        ),
    ]
