# Generated by Django 3.2.7 on 2021-09-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='sort_order',
        ),
    ]
