# Generated by Django 3.2.7 on 2021-09-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0002_remove_series_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='シリーズ名'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='品種名'),
        ),
    ]
