# Generated by Django 3.2.7 on 2021-09-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0003_auto_20210916_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuka.series', verbose_name='シリーズ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuka.variety', verbose_name='品種'),
        ),
    ]
