# Generated by Django 3.2.7 on 2021-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0004_auto_20210916_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(max_length=50, verbose_name='品種名'),
        ),
    ]
