# Generated by Django 3.2.7 on 2021-09-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0005_alter_variety_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuka.variety', verbose_name='品種'),
        ),
    ]
