# Generated by Django 3.2.7 on 2021-09-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50, verbose_name='シリーズ名'),
        ),
    ]
