# Generated by Django 3.2.7 on 2021-09-16 14:54

from django.db import migrations, models
import yuka.function


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0010_alter_series_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSVReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    upload_to=yuka.function.upload_product_image_path)),
                ('h_per_5', models.FloatField()),
                ('h_per_50', models.FloatField()),
                ('h_per_95', models.FloatField()),
                ('s_per_5', models.FloatField()),
                ('s_per_50', models.FloatField()),
                ('s_per_95', models.FloatField()),
                ('v_per_5', models.FloatField()),
                ('v_per_50', models.FloatField()),
                ('v_per_95', models.FloatField()),
            ],
        ),
    ]
