# Generated by Django 3.2.7 on 2021-09-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0011_hsvreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsvreport',
            name='h_per_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='h_per_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='h_per_95',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='s_per_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='s_per_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='s_per_95',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='v_per_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='v_per_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsvreport',
            name='v_per_95',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
