# Generated by Django 3.2.7 on 2021-09-17 05:00

from django.db import migrations, models
import yuka.function


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0012_auto_20210917_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsvreport',
            name='hsv_image',
            field=models.ImageField(
                default=1, upload_to=yuka.function.upload_product_image_path),
            preserve_default=False,
        ),
    ]
