# Generated by Django 3.2.7 on 2021-09-17 05:03

from django.db import migrations, models
import yuka.function


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0013_hsvreport_hsv_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsvreport',
            name='hsv_image',
            field=models.ImageField(
                blank=True, null=True, upload_to=yuka.function.upload_product_image_path),
        ),
    ]
