# Generated by Django 3.2.7 on 2021-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0014_alter_hsvreport_hsv_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsvreport',
            name='hsv_image',
        ),
        migrations.AddField(
            model_name='hsvreport',
            name='hsv_report',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
