# Generated by Django 3.2.7 on 2021-09-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuka', '0016_auto_20210918_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreport',
            old_name='rbg1_b',
            new_name='rgb1_b',
        ),
    ]
